# Generated by Django 3.1.7 on 2021-04-17 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '__first__'),
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100)),
                ('char_number', models.CharField(blank=True, max_length=90)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('first_login', models.BooleanField(default=True)),
                ('next_email_verify_send', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_code', models.CharField(blank=True, max_length=15)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Стандарт'), (2, 'Блогер')], default=1)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('balance_etg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etg_user', to='finance.balanceetg')),
                ('balance_etggold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etggold_user', to='finance.balanceetggold')),
                ('balance_usd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usd_user', to='finance.balanceusd')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferalCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referal_code', models.CharField(max_length=50, unique=True)),
                ('level1_percent', models.DecimalField(decimal_places=2, default=5, max_digits=15)),
                ('level2_percent', models.DecimalField(decimal_places=2, default=3, max_digits=15)),
                ('level3_percent', models.DecimalField(decimal_places=2, default=2, max_digits=15)),
                ('level4_percent', models.DecimalField(decimal_places=2, default=1.5, max_digits=15)),
                ('level5_percent', models.DecimalField(decimal_places=2, default=1, max_digits=15)),
                ('level6_percent', models.DecimalField(decimal_places=2, default=0.5, max_digits=15)),
                ('level7_percent', models.DecimalField(decimal_places=2, default=0.5, max_digits=15)),
                ('level8_percent', models.DecimalField(decimal_places=2, default=0.5, max_digits=15)),
                ('level9_percent', models.DecimalField(decimal_places=2, default=0.5, max_digits=15)),
                ('level10_percent', models.DecimalField(decimal_places=2, default=0.5, max_digits=15)),
                ('all_levels_earned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('level1_earned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('level2_earned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('level3_earned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('level4_earned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('level5_earned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('level6_earned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('level7_earned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('level8_earned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('level9_earned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('level10_earned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('referal_list', models.ManyToManyField(blank=True, related_name='referal_list_card', to=settings.AUTH_USER_MODEL)),
                ('referals_level_1', models.ManyToManyField(blank=True, related_name='referal_owner1_card', to=settings.AUTH_USER_MODEL)),
                ('referals_level_10', models.ManyToManyField(blank=True, related_name='referal_owner10_card', to=settings.AUTH_USER_MODEL)),
                ('referals_level_2', models.ManyToManyField(blank=True, related_name='referal_owner2_card', to=settings.AUTH_USER_MODEL)),
                ('referals_level_3', models.ManyToManyField(blank=True, related_name='referal_owner3_card', to=settings.AUTH_USER_MODEL)),
                ('referals_level_4', models.ManyToManyField(blank=True, related_name='referal_owner4_card', to=settings.AUTH_USER_MODEL)),
                ('referals_level_5', models.ManyToManyField(blank=True, related_name='referal_owner5_card', to=settings.AUTH_USER_MODEL)),
                ('referals_level_6', models.ManyToManyField(blank=True, related_name='referal_owner6_card', to=settings.AUTH_USER_MODEL)),
                ('referals_level_7', models.ManyToManyField(blank=True, related_name='referal_owner7_card', to=settings.AUTH_USER_MODEL)),
                ('referals_level_8', models.ManyToManyField(blank=True, related_name='referal_owner8_card', to=settings.AUTH_USER_MODEL)),
                ('referals_level_9', models.ManyToManyField(blank=True, related_name='referal_owner9_card', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referal_card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('address', models.GenericIPAddressField(unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_banned', models.BooleanField(default=False)),
                ('ref_code', models.SlugField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferalsAdded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500)),
                ('level_number', models.CharField(blank=True, default='0', max_length=5)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('referal_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.referalcard')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referal_added', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='ip',
            field=models.ManyToManyField(blank=True, related_name='user', to='users.UserIP'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_number_user', to='users.userphonenumber'),
        ),
        migrations.AddField(
            model_name='user',
            name='transaction_history',
            field=models.ManyToManyField(blank=True, related_name='transaction_history_user', to='finance.TransactionHistory'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
