# Generated by Django 3.1.7 on 2021-04-17 18:14

from django.db import migrations, models
import django.utils.timezone
import landing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новый ответ', max_length=500)),
                ('text', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новая новость', max_length=500)),
                ('picture', models.ImageField(default='news/default/default_pic.jpg', upload_to=landing.models.news_pic_path)),
                ('text', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новая цель', max_length=500)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
