# Generated by Django 3.1.7 on 2021-04-17 18:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceETG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=9, default=0, max_digits=500)),
                ('balance_in_usd', models.DecimalField(decimal_places=2, default=0, max_digits=500)),
                ('staking_full_amount', models.DecimalField(decimal_places=10, default=0, max_digits=500)),
                ('staking_full_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=500)),
                ('account_code', models.SlugField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceETGGOLD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=9, default=0, max_digits=500)),
                ('balance_in_usd', models.DecimalField(decimal_places=2, default=0, max_digits=500)),
                ('staking_full_amount', models.DecimalField(decimal_places=10, default=0, max_digits=500)),
                ('staking_full_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=500)),
                ('account_code', models.SlugField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceUSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=500)),
                ('account_code', models.SlugField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etgCount', models.DecimalField(decimal_places=10, default=0, max_digits=500)),
                ('etgBuyCount', models.DecimalField(decimal_places=10, default=0, max_digits=500)),
                ('realetgBuyCount', models.DecimalField(decimal_places=10, default=0, max_digits=500)),
                ('rateETGinUSD', models.DecimalField(decimal_places=2, default=0, max_digits=500)),
                ('rateETGGOLDinUSD', models.DecimalField(decimal_places=2, default=0, max_digits=500)),
                ('rateETGGOLDinETG', models.DecimalField(decimal_places=10, default=0, max_digits=500)),
                ('is_enable_withdrawal', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Системные настройки',
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Депозит'), (2, 'Вывод'), (3, 'Перевод между счетами'), (4, 'Неизвестно')], default=4)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Выполнен'), (2, 'Отменен'), (3, 'В процессе'), (4, 'Неизвестно')], default=4)),
                ('from_type', models.PositiveSmallIntegerField(choices=[(1, 'ETG'), (2, 'USD'), (3, 'ETGGOLD'), (4, 'ВНЕШНИЙ')], default=4)),
                ('from_amount', models.DecimalField(decimal_places=10, default=0, max_digits=500)),
                ('from_old_balance', models.DecimalField(decimal_places=10, default=0, max_digits=500)),
                ('from_new_balance', models.DecimalField(decimal_places=10, default=0, max_digits=500)),
                ('from_new_balance_in_usd', models.DecimalField(decimal_places=2, default=0, max_digits=500)),
                ('to_type', models.PositiveSmallIntegerField(choices=[(1, 'ETG'), (2, 'USD'), (3, 'ETGGOLD'), (4, 'ВНЕШНИЙ')], default=4)),
                ('to_amount', models.DecimalField(decimal_places=10, default=0, max_digits=500)),
                ('to_amount_in_usd', models.DecimalField(decimal_places=2, default=0, max_digits=500)),
                ('to_old_balance', models.DecimalField(decimal_places=10, default=0, max_digits=500)),
                ('to_new_balance', models.DecimalField(decimal_places=10, default=0, max_digits=500)),
                ('to_new_balance_in_usd', models.DecimalField(decimal_places=2, default=0, max_digits=500)),
            ],
        ),
        migrations.CreateModel(
            name='StakingETGHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_before', models.DecimalField(decimal_places=10, default=0, max_digits=500)),
                ('balance_new', models.DecimalField(decimal_places=10, default=0, max_digits=500)),
                ('staking_amount', models.DecimalField(decimal_places=10, default=0, max_digits=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staking_etg_history', to='finance.balanceetg')),
            ],
        ),
        migrations.CreateModel(
            name='StakingETGGOLDHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_before', models.DecimalField(decimal_places=10, default=0, max_digits=500)),
                ('balance_new', models.DecimalField(decimal_places=10, default=0, max_digits=500)),
                ('staking_amount', models.DecimalField(decimal_places=10, default=0, max_digits=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staking_etggold_history', to='finance.balanceetggold')),
            ],
        ),
    ]
