"""
Django settings for etgProject project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'gf7@gna+i7i%q!vau95@wl*gb*2f093nek0xs(qh3q!#m7!8@+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

TIME_ZONE = 'Europe/Moscow'

AUTH_USER_MODEL = 'users.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',

    'users',
    'finance',
    'frontend',
    'landing',
    'staff',
    'api',

    'phonenumber_field',
    'celery',
    'redis',
    'django_crontab',
    'imagekit',
    'solo',
]

PHONENUMBER_DB_FORMAT = 'INTERNATIONAL'

SMSCRU_LOGIN = "andreyvelikanovv"            # логин клиента
SMSCRU_PASSWORD = "Andreyvel0099"    # пароль
SMSCRU_POST = False                # использовать метод POST
SMSCRU_HTTPS = False                # использовать HTTPS протокол
SMSCRU_CHARSET = "utf-8"            # кодировка сообщения (windows-1251 или koi8-r), по умолчанию используется utf-8
SMSCRU_DEBUG = False                # флаг отладки

# Константы для отправки SMS по SMTP
SMSCRU_SMTP_FROM = "api@smsc.ru"        # e-mail адрес отправителя
SMSCRU_SMTP_SERVER = "send.smsc.ru"    # адрес smtp сервера
SMSCRU_SMTP_LOGIN = ""                    # логин для smtp сервера
SMSCRU_SMTP_PASSWORD = ""

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'etgProject.urls'

STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_URL = '/static/'
#STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'finance.context_proccessors.load_finance_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'etgProject.wsgi.application'


# DATABASE
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
    }
}
SOLO_ADMIN_SKIP_OBJECT_LIST_PAGE = False


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

"""
EMAIL_HOST = 'debugmail.io'
EMAIL_PORT = 25
EMAIL_HOST_USER = "andreyvelikanovv@gmail.com"
EMAIL_HOST_PASSWORD = "a85c2240-54bb-11eb-875f-87492950ae45"
"""
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = "etgtestemail@gmail.com"
EMAIL_HOST_PASSWORD = "AndreyVel0099"


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True

USE_L10N = True

USE_TZ = True



REDIS_HOST = 'localhost'
REDIS_PORT = 6379

# CELERY
# Celery Configuration Options
CELERY_TIMEZONE = os.getenv("CELERY_TIMEZONE")
CELERY_TASK_TRACK_STARTED = os.getenv("CELERY_TASK_TRACK_STARTED")
CELERY_TASK_TIME_LIMIT = os.getenv("CELERY_TASK_TIME_LIMIT")

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")
CELERY_BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND")
CELERY_TASK_SERIALIZER = os.getenv("CELERY_TASK_SERIALIZER")
CELERY_RESULT_SERIALIZER = os.getenv("CELERY_RESULT_SERIALIZER")





